apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jwt-service-broker
    version: v1
  name: jwt-service-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-service-broker
      version: v1
  template:
    metadata:
      labels:
        app: jwt-service-broker
        version: v1
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:///dev/./urandom
        image: example/jwt-service-broker:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        name: jwt-service-broker
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        securityContext:
          privileged: false

- apiVersion: servicecatalog.k8s.io/v1beta1
  kind: ClusterServiceBroker
  metadata:
    name: ansible-service-broker
  spec:
    url: https://asb.ansible-service-broker.svc:1338/ansible-service-broker/
    authInfo:
      ${{BROKER_AUTH}}
    insecureSkipTLSVerify: true
